global:
  enabled: true
  environment: prod
  namespace: pos-prod

backend:
  replicas: 3
  image:
    tag: latest

  resources:
    requests:
      cpu: "200m"
      memory: "250Mi"

  autoscaling:
    enabled: false

frontend::
  replicas: 3
  image:
    tag: latest

  resources:
    requests:
      cpu: "200m"
      memory: "250Mi"

  autoscaling:
    enabled: false

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  persistence:
    size: 400Mi

config:
  jpa:
    hibernate_ddl_auto: "validate"
    show_sql: "true"
  otel:
    exporter:
      otlp:
        endpoint: "http://alloy.monitoring.svc.cluster.local:4317"
    service_name: "pos-backend-dev"
  java_tool_options: "-javaagent:/app/otel-javaagent.jar -Dotel.javaagent.debug=true"