global:
  enabled: true
  environment: dev
  namespace: pos
  domain: pos-dev.local

backend:
  replicas: 2
  pdb:
    enabled: true
    minAvailable: 0
    maxUnavailable: 1
  image:
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"

  probes:
    port: 8082
    startup:
      initialDelaySeconds: 60

  autoscaling:
    enabled: true
    mode: keda
    hpa:
      minReplicas: 1
      maxReplicas: 6
      cpuAverageUtilization: 80
      memoryAverageUtilization: 85
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policy:
            type: Percent
            value: 50
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 1
              periodSeconds: 15
    keda:
      minReplicaCount: 1
      maxReplicaCount: 6
      cpuAverageUtilization: 80
      memoryAverageUtilization: 85
      timezone: "UTC"
      start: "0 22 * * *"
      end: "0 8 * * *"
      desiredReplicas: "0"

frontend:
  replicas: 1
  pdb:
    enabled: true
    minAvailable: 0
    maxUnavailable: 1
  image:
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: "100m"
      memory: "250Mi"

  autoscaling:
    enabled: true
    mode: keda
    hpa:
      minReplicas: 1
      maxReplicas: 4
      cpuAverageUtilization: 80
      memoryAverageUtilization: 85
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policy:
            type: Percent
            value: 50
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 1
              periodSeconds: 15
    keda:
      minReplicaCount: 1
      maxReplicaCount: 4
      cpuAverageUtilization: 70
      memoryAverageUtilization: 75
      timezone: "UTC"
      start: "0 22 * * *"
      end: "0 8 * * *"
      desiredReplicas: "0"

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  persistence:
    size: 200Mi

config:
  jpa:
    hibernate_ddl_auto: "validate"
    show_sql: "true"
  otel:
    exporter:
      otlp:
        endpoint: "http://alloy-receiver.monitoring.svc.cluster.local:4317"
    service_name: "pos-backend-dev"
  java_tool_options: "-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.javaagent.debug=false"