global:
  enabled: true
  environment: prod
  namespace: pos-prod
  domain: pos.local

backend:
  replicas: 3
  image:
    tag: latest

  resources:
    requests:
      cpu: "200m"
      memory: "250Mi"

  probes:
    port: 8082
    startup:
      initialDelaySeconds: 90

  autoscaling:
    enabled: true
    mode: keda
    hpa:
      minReplicas: 2
      maxReplicas: 10
      cpuAverageUtilization: 70
      memoryAverageUtilization: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policy:
            type: Percent
            value: 50
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 2
              periodSeconds: 15
    keda:
      minReplicaCount: 2
      maxReplicaCount: 10
      cpuAverageUtilization: 70
      memoryAverageUtilization: 80

frontend:
  replicas: 2
  image:
    tag: latest

  resources:
    requests:
      cpu: "100m"
      memory: "150Mi"

  autoscaling:
    enabled: true
    mode: keda
    hpa:
      minReplicas: 2
      maxReplicas: 8
      cpuAverageUtilization: 70
      memoryAverageUtilization: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policy:
            type: Percent
            value: 50
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 2
              periodSeconds: 15
    keda:
      minReplicaCount: 2
      maxReplicaCount: 8
      cpuAverageUtilization: 70
      memoryAverageUtilization: 80

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  persistence:
    size: 400Mi

config:
  jpa:
    hibernate_ddl_auto: "validate"
    show_sql: "true"
  otel:
    exporter:
      otlp:
        endpoint: "http://alloy-receiver.monitoring.svc.cluster.local:4317"
    service_name: "pos-backend-prod"
  java_tool_options: "-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.javaagent.debug=false"