global:
  enabled: true
  environment: dev
  namespace: pos

backend:
  replicas: 2
  image:
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"

  autoscaling:
    enabled: false

frontend:
  replicas: 1
  image:
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: "100m"
      memory: "250Mi"

  autoscaling:
    enabled: false

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  persistence:
    size: 200Mi

config:
  jpa:
    hibernate_ddl_auto: "validate"
    show_sql: "true"
  otel:
    exporter:
      otlp:
        endpoint: "http://alloy-receiver.monitoring.svc.cluster.local:4317"
    service_name: "pos-backend-dev"
  java_tool_options: "-javaagent:/otel/opentelemetry-javaagent.jar -Dotel.javaagent.debug=false"