apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langfuse.fullname" . }}-config
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.config.DATABASE_URL | quote }}
  REDIS_PASSWORD: {{ .Values.config.REDIS_PASSWORD | quote }}
  NEXTAUTH_SECRET: {{ .Values.config.NEXTAUTH_SECRET | quote }}
  NEXTAUTH_URL: {{ .Values.config.NEXTAUTH_URL | quote }}
  SALT: {{ .Values.config.SALT | quote }}
  TELEMETRY_ENABLED: {{ .Values.config.TELEMETRY_ENABLED | quote }}
