global:
  environment: prod
  namespace: pos-prod

backend:
  replicas: 3
  image:
    tag: latest

  resources:
    requests:
      cpu: "200m"
      memory: "250Mi"

  autoscaling:
    enabled: false

frontend::
  replicas: 3
  image:
    tag: latest

  resources:
    requests:
      cpu: "200m"
      memory: "250Mi"

  autoscaling:
    enabled: false

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  persistence:
    size: 400Mi

ingress:
  host: pos-prod.local

config:
  jpa:
    hibernate_ddl_auto: "validate"
    show_sql: "true"