global:
  environment: prod
  namespace: pos-prod

backend:
  replicas: 3
  image:
    tag: latest

  resources:
    requests:
      cpu: "200m"
      memory: "250Mi"

  autoscaling:
    enabled: false

frontend::
  replicas: 3
  image:
    tag: latest

  resources:
    requests:
      cpu: "200m"
      memory: "250Mi"

  autoscaling:
    enabled: false

mysql:
  persistence:
    size: 500Mi

config:
  jpa:
    hibernate_ddl_auto: "create-drop"
    show_sql: "true"