{{- if .Values.global.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pos-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pos.commonLabels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pos-backend-service
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pos-frontend-service
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
