{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pos.commonLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.pvcAutoscaler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pvcAutoscaler.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pos.commonLabels" . | nindent 4 }}
{{- end }}