service:
  type: ClusterIP

# persistence:
#   enabled: true
#   storageClassName: standard
#   size: 3Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 256Mi

adminUser: admin
adminPassword: ChangeMeStrong

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: kubernetes
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kube-state-metrics-v2:
      gnetId: 13332
      revision: 12
      datasource: Mimir
    kubernetes-cluster-monitoring:
      gnetId: 15661
      revision: 2
      datasource: Mimir

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        isDefault: false
      - name: Mimir
        type: prometheus
        access: proxy
        url: http://mimir-nginx.monitoring.svc.cluster.local/prometheus
        isDefault: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3100
        isDefault: false
      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: http://mimir-nginx.monitoring.svc.cluster.local
        isDefault: false
        jsonData:
          implementation: mimir
          handleGrafanaManagedAlerts: false