alloy:
  configMap:
    create: false
    enableReporting: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

  rbac:
    create: true

  serviceAccount:
    create: true

  controller:
    type: "daemonset"
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              namespaces:
                - monitoring
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"

alloy-receiver:
  configMap:
    create: false
    enableReporting: false

  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 150m
      memory: 256Mi

  rbac:
    create: true

  serviceAccount:
    create: true

  controller:
    type: "deployment"

# KSM (Kube-State-Metrics) configuration
ksm:
  prometheusScrape: false
  
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  
  service:
    type: ClusterIP
    port: 8080
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
  
  # collectors:
  #   - certificatesigningrequests
  #   - configmaps
  #   - cronjobs
  #   - daemonsets
  #   - deployments
  #   - endpoints
  #   - horizontalpodautoscalers
  #   - ingresses
  #   - jobs
  #   - limitranges
  #   - namespaces
  #   - nodes
  #   - persistentvolumeclaims
  #   - persistentvolumes
  #   - poddisruptionbudgets
  #   - pods
  #   - replicasets
  #   - replicationcontrollers
  #   - resourcequotas
  #   - secrets
  #   - services
  #   - statefulsets
  #   - storageclasses
