alloy:
  configMap:
    create: false
    name: alloy-config
    key: config.alloy
    enableReporting: false

rbac:
  create: true

serviceAccount:
  create: true

controller:
  type: "daemonset"
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            namespaces:
              - monitoring
            labelSelector:
              matchExpressions:
                - key: app
                  operator: Exists
            topologyKey: "kubernetes.io/hostname"
