{{- if .Values.apps.alertingRules.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alerting-rules-{{ .Values.apps.alertingRules.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability
  source:
    repoURL: https://github.com/rprakashdass/gitops.git
    targetRevision: local-server
    path: platform/alerting/{{ .Values.apps.alertingRules.env }}
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
