apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alerting-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability
  sources:
  - repoURL: https://github.com/rprakashdass/gitops.git
    targetRevision: local-server
    path: platform/observability/alerting
    helm:
      valueFiles:
        - values.yaml
  - repoURL: https://github.com/rprakashdass/gitops.git
    targetRevision: local-server
    path: platform/alerting/{{ .Values.apps.alertingConfig.rulesEnv }}
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
