{{- if .Values.apps.grafana.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.15
      helm:
        releaseName: grafana
        valueFiles:
          - $values/platform/observability/grafana/values.yaml
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      ref: values
{{- end }}
