{{- if .Values.apps.minio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://charts.min.io/
      chart: minio
      targetRevision: 5.*
      helm:
        releaseName: minio
        valueFiles:
          - $values/platform/observability/minio/values.yaml
    - repoURL: https://github.com/rprakashdass/gitops.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
