{{- if .Values.apps.posSystemProd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-system-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: springboot-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: pos-prod
  sources:
    - repoURL: https://github.com/rprakashdass/gitops.git
      targetRevision: main
      path: springboot-apps/pos/pos-system
      helm:
        valueFiles:
          - base-values.yaml
          - values-prod.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}
