{{- if .Values.apps.posSystem.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: springboot-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: pos-dev
  sources:
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      ref: values
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      path: springboot-apps
      helm:
        valueFiles:
          - $values/values/values-dev.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}
