{{- if .Values.apps.minio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.3.0"
      helm:
        releaseName: tempo
        valueFiles:
          - $values/platform/observability/tempo/values.yaml
    - repoURL: {{ .Values.global.repoURL }}
      targetRevision: {{ .Values.global.targetRevision }}
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
