apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly

  policy.csv: |
    p, role:admin, *, *, */*, allow

    p, role:dev, applications, get, springboot-apps/*, allow
    p, role:dev, applications, sync, springboot-apps/*, allow
    p, role:dev, logs, get, springboot-apps/*, allow
    p, role:dev, exec, create, springboot-apps/*, allow
    p, role:dev, projects, get, springboot-apps, allow

    g, admin, role:admin
    g, dev, role:dev
    g, prakash, role:admin
