apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  accounts.admin.password: "$2a$10$WkboxrjFykBpsa72Z9WLLOIwYVsAg.6GUgMQNlVYOk3WPWhAijWNy"
  accounts.dev.password: "$2a$10$xSjZu0ysZ19QwbQZYoal9.Tab2rfzGfCptBrWRZKRVbdfE3dYRVZu"