apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  application.resourceTrackingMethod: annotation
  admin.enabled: "true"

  accounts.admin: login
  accounts.dev: login

  timeout.reconciliation: 300s