apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir-rules-sync
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mimir-rules-sync
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mimir-rules-sync
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mimir-rules-sync
subjects:
- kind: ServiceAccount
  name: mimir-rules-sync
  namespace: monitoring
