# ArgoCD Helm Chart Values
# Official chart: https://github.com/argoproj/argo-helm

# Global settings
global:
  domain: argocd.local

# Server configuration
server:
  insecure: true

  service:
    port: 80

  # Ingress configuration (optional)
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: argocd.rprakashdass.in
        paths:
          - path: /
            pathType: Prefix

# Controller configuration
controller:
  # Increase resource limits if needed
  resources:
    limits:
      cpu: 200m
      memory: 258Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Repo server configuration  
repoServer:
  resources:
    limits:
      cpu: 200m
      memory: 258Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Redis
redis:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

# Dex (SSO)
dex:
  enabled: true

# Application Set Controller
applicationSet:
  enabled: true

# Notifications Controller
notifications:
  enabled: true

configs:
  params:
    server.insecure: true
