apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  source:
    path: argocd/argocd-apps/
  definition:
    namespace: argocd
  syncPolicy:
    automated:
      prune: false