ollama:
  enabled: false

ollamaUrls:
  - http://ollama.ollama.svc.cluster.local:11434

pipelines:
  enabled: false

ingress:
  enabled: true
  class: traefik
  host: chat.local

persistence:
  enabled: true
  size: 2Gi