{{- if .Values.global.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pos-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pos.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  pos_db_username: {{ .Values.mysql.auth.username | b64enc | quote }}
  pos_db_password: {{ .Values.mysql.auth.password | b64enc | quote }}
{{- end }}
