{{- if .Values.global.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pos-db-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pos.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app: pos-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
{{- end }}
