knative:
  enabled: false

replicaCount: 1

ollama:
  models:
    pull: [llama3.2:3b]
    run: [llama3.2:3b]
    create: []

ingress:
  enabled: true
  className: traefik

resources:
  requests:
    cpu: "3000m"
    memory: "4Gi"
  limits:
    cpu: "6000m"
    memory: "6Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  size: 20Gi

extraEnv:
  - name: OLLAMA_KEEP_ALIVE
    value: "10m"