apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingress
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://github.com/rprakashdass/gitops.git
    targetRevision: main
    path: platform
    directory:
      include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
