apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-system-prod
  namespace: argocd
spec:
  project: springboot-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: pos-prod
  sources:
    - repoURL: https://github.com/rprakashdass/gitops.git
      targetRevision: main
      path: springboot-apps/pos-system
      helm:
        valueFiles:
          - base-values.yaml
          - values-prod.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true