apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pos-system
  namespace: argocd
spec:
  project: springboot-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: pos
  sources:
    - repoURL: https://github.com/rprakashdass/gitops.git
      targetRevision: main
      path: springboot-apps/pos/pos-system
      helm:
        valueFiles:
          - base-values.yaml
          - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true