apps:
  alloy:
    enabled: true
  argoCdRbac:
    enabled: true
  grafana:
    enabled: true
  loki:
    enabled: true
  mimir:
    enabled: true
  minio:
    enabled: true
  platformIngress:
    enabled: true
  posSystem:
    enabled: true
  posSystemProd:
    enabled: true
  tempo:
    enabled: true
  vpa:
    enabled: true
    chartVersion: "1.9.3"