apps:
  alloy:
    enabled: true
  argoCdRbac:
    enabled: true
  grafana:
    enabled: true
  loki:
    enabled: false
  mimir:
    enabled: true
  minio:
    enabled: true
  platformIngress:
    enabled: true
  posSystem:
    enabled: true
  posSystemProd:
    enabled: false
  tempo:
    enabled: false
  vpa:
    enabled: false
    chartVersion: "4.11.0"
  prometheus-alertmanager:
    enabled: true
  alertingConfig:
    rulesEnv: production