apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.5.x
    helm:
      releaseName: grafana
      valueFiles:
        - $values/values/grafana-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.*
      helm:
        releaseName: grafana
        valueFiles:
          - $values/values/grafana-values.yaml
    - repoURL: https://github.com/rprakashdass/gitops.git
      targetRevision: main
      ref: values