apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: mimir
    helm:
      releaseName: mimir
      valueFiles:
        - $values/values/mimir-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      helm:
        releaseName: mimir
        valueFiles:
          - $values/values/mimir-values.yaml
    - repoURL: https://github.com/rprakashdass/gitops.git
      targetRevision: main
      ref: values