apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 3.0.x
      helm:
        releaseName: mimir
        valueFiles:
          - $values/values/mimir-values.yaml
  
    - repoURL: https://github.com/rprakashdass/gitops.git
      targetRevision: main
      ref: values