alertmanager:
  enabled: true
  config:
    # Load files from the alerting directory
    # Contact points (receivers)
    receivers:
      path: /etc/alertmanager-config/contact-points.yaml

    # Routing rules
    route:
      path: /etc/alertmanager-config/routes.yaml

    # Notification templates
    templates:
    - /etc/alertmanager-config/templates/*.tmpl

  # Mount the alerting config as a volume
  extraVolumes:
  - name: alertmanager-config
    configMap:
      name: alertmanager-config
  - name: alertmanager-slack-secret
    secret:
      secretName: alertmanager-slack

  extraVolumeMounts:
  - name: alertmanager-config
    mountPath: /etc/alertmanager-config
    readOnly: true

  # Mount the Slack secret as a volume
  extraSecretMounts:
  - name: alertmanager-slack-secret
    mountPath: /etc/alertmanager/secrets
    readOnly: true

server:
  # Load alerting rules from the alerting directory
  additionalRuleLabels:
    repo: gitops

  additionalRules:
    path: /etc/prometheus-rules/*

  extraVolumes:
  - name: prometheus-rules
    configMap:
      name: prometheus-rules

  extraVolumeMounts:
  - name: prometheus-rules
    mountPath: /etc/prometheus-rules
    readOnly: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
  hosts:
    - host: alertmanager.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

configmapReload:
  enabled: true