{{- if .Values.global.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-config

data:
  # Spring Boot Database connection
  SPRING_DATASOURCE_URL: {{ .Values.config.database.url }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.jpa.hibernate_ddl_auto }}
  SPRING_JPA_SHOW_SQL: {{ .Values.config.jpa.show_sql | quote }}
  NEXT_PUBLIC_API_BASE_URL: {{ .Values.config.api.base_url }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otel.exporter.otlp.endpoint }}
  OTEL_SERVICE_NAME: {{ .Values.config.otel.service_name }}
  JAVA_TOOL_OPTIONS: {{ .Values.config.java_tool_options | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_ENDPOINT: "http://alloy-receiver.observability.svc.cluster.local:4317"
{{- end }}