{{- if eq .Values.backend.autoscaling.mode "keda" }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pos-backend-scaledobject
spec:
  scaleTargetRef:
    name: pos-backend
  minReplicaCount: {{ .Values.backend.autoscaling.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.backend.autoscaling.keda.maxReplicaCount }}
  triggers:
    - type: cron
      metadata:
        timezone: {{ .Values.backend.autoscaling.keda.timezone | default "UTC" | quote }}
        start: {{ .Values.backend.autoscaling.keda.start | default "0 22 * * *" | quote }}
        end: {{ .Values.backend.autoscaling.keda.end | default "0 8 * * *" | quote }}
        desiredReplicas: {{ .Values.backend.autoscaling.keda.desiredReplicas | default "0" | quote }}
    - type: cpu
      metadata:
        type: Utilization
        value: "{{ .Values.backend.autoscaling.keda.cpuAverageUtilization }}"
    - type: memory
      metadata:
        type: Utilization
        value: "{{ .Values.backend.autoscaling.keda.memoryAverageUtilization }}"
{{- end }}