{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pos-frontend-scaledobject
spec:
  scaleTargetRef:
    name: pos-frontend
  minReplicaCount: {{ .Values.frontend.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.frontend.autoscaling.maxReplicaCount }}
  triggers:
    - type: cpu
      metadata:
        metricType: Utilization
        value: "{{ .Values.frontend.autoscaling.cpuAverageUtilization }}"
    - type: memory
      metadata:
        metricType: Utilization
        value: "{{ .Values.frontend.autoscaling.memoryAverageUtilization }}"
  {{- if .Values.frontend.autoscaling.behavior }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
{{ toYaml .Values.frontend.autoscaling.behavior | indent 8 }}
  {{- end }}
{{- end }}