{{- if .Values.backend.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pos-backend-scaledobject
spec:
  scaleTargetRef:
    name: pos-backend
  minReplicaCount: {{ .Values.backend.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.backend.autoscaling.maxReplicaCount }}
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "{{ .Values.backend.autoscaling.cpuAverageUtilization }}"
    - type: memory
      metadata:
        type: Utilization
        value: "{{ .Values.backend.autoscaling.memoryAverageUtilization }}"
  {{- if .Values.backend.autoscaling.behavior }}
  behavior:
{{ toYaml .Values.backend.autoscaling.behavior | indent 4 }}
  {{- end }}
{{- end }}