{{- if .Values.frontend.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pos-frontend-scaledobject
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pos.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pos-frontend
  minReplicaCount: {{ .Values.frontend.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.frontend.autoscaling.maxReplicaCount }}
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "{{ .Values.frontend.autoscaling.cpuAverageUtilization }}"
    - type: memory
      metricType: Utilization
      metadata:
        value: "{{ .Values.frontend.autoscaling.memoryAverageUtilization }}"
  {{- if .Values.frontend.autoscaling.behavior }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        {{- toYaml .Values.frontend.autoscaling.behavior | nindent 8 }}
  {{- end }}
{{- end }}
