global:
  commonLabels:
    app: tempo
labels:
  app: tempo
tempo:
  reportingEnabled: false
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo
        endpoint: minio.monitoring.svc.cluster.local:9000
        access_key: loki
        secret_key: loki12345
        insecure: true