global:
  commonLabels:
    app: tempo
labels:
  app: tempo
tempo:
  reportingEnabled: false
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo
        endpoint: minio.minio.svc.cluster.local:9000
        accessKey: loki
        secretKey: loki12345
        insecure: true